import type { GenotypeEntry } from './genomeParser';

export const exportTo23andMe = (entries: GenotypeEntry[], person: 'father' | 'mother' | 'son1' | 'son2'): string => {
    const header = `# This file was generated by Genome Dashboard
# It mimics the 23andMe raw data format.
# rsid\tchromosome\tposition\tgenotype
`;

    const lines = entries.map(e => {
        let genotype = e[person];
        // 23andMe typically uses just the letters (e.g., "AG", "CC", "T")
        // or "--" for no call.
        if (!genotype || genotype.length === 0) genotype = '--';
        
        return `${e.rsid}\t${e.chromosome}\t${e.position}\t${genotype}`;
    });

    return header + lines.join('\n');
};

